### ISSUE TITLE
No method to stop the WebTransport server?

### ISSUE THREAD

**Issue by adriancable** [langhuihui/WebTransport-Go#1]
Hi - after starting the server by calling Run(), it appears there's no clean way to stop it, short of stopping the whole process. Can you add a Stop() method so we can cleanly stop a server and/or allow the object returned by NewWebTransportServer to be garbage collected?

My specific application here is the need to periodically change the PEM/KEY of the service while it's running.

**Comment by langhuihui** [comment]
you can now use context to stop the process

**Comment by adriancable** [comment]
That looks great - thank you for this change!
